#!/usr/bin/env bash
# cmd/ferryman/NOTICES.txt を生成する。GUI バイナリに go:embed され、
# Menu → Licenses で表示される。
#
#     script/gen-licenses.sh
#
# ferryman は単体の実行ファイル（.exe / .app）として配られるので、ライセンス本文を
# 置ける「添付ドキュメント」が無い。MIT / BSD / Apache-2.0 はいずれもバイナリ配布時に
# 著作権表示と本文を伴わせることを条件にしているため、バイナリ自身が抱えている。
#
# 依存が変わったら実行して差分をコミットすること。CI (.github/workflows/ci.yml) が
# 生成物と突き合わせるので、忘れると落ちる。
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${root}"
out="${1:-${root}/cmd/ferryman/NOTICES.txt}"

# 依存は GOOS で変わる（go-winio は windows、godbus は linux だけ）。どの OS 向けの
# バイナリにも同じ NOTICES.txt が入る以上、配布する 3 つの和集合を採る。
# CGO_ENABLED=1 は glfw のように cgo ファイルしか持たないパッケージを落とさないため
# （go list はコンパイラを呼ばないので、クロスでもツールチェインは要らない）。
mods="$(
  for os in darwin linux windows; do
    GOOS="${os}" CGO_ENABLED=1 go list -deps \
      -f '{{with .Module}}{{if .Version}}{{.Path}} {{.Version}} {{.Dir}}{{end}}{{end}}' \
      ./cmd/ferryman
  done | sort -u
)"

# 見出しの区切り線
rule="--------------------------------------------------------------------------"

emit_file() { # <path>  CRLF を落として本文を流す
  tr -d '\r' < "$1"
  echo
}

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

{
  cat <<'HEADER'
Ferryman — license notices

This file is generated by script/gen-licenses.sh. Do not edit it by hand.

Ferryman is distributed as a single self-contained executable. Everything it
statically links or embeds is listed below, in full, as those licenses require.

HEADER

  echo "${rule}"
  echo "Ferryman"
  echo "${rule}"
  echo
  emit_file "${root}/LICENSE.txt"

  echo "${rule}"
  echo "Go modules linked into the binary"
  echo "${rule}"
  echo

  while read -r path version dir; do
    [ -n "${path}" ] || continue
    # トップレベルの LICENSE / COPYING / NOTICE だけを見る。Apache-2.0 の NOTICE の
    # ように 1 モジュールが複数持つことがあるので全部拾う
    files="$(find "${dir}" -maxdepth 1 -type f \
      \( -iname 'LICENSE' -o -iname 'LICENCE' -o -iname 'COPYING' -o -iname 'NOTICE' \
         -o -iname 'LICENSE.*' -o -iname 'LICENCE.*' -o -iname 'COPYING.*' -o -iname 'NOTICE.*' \) \
      | sort)"
    if [ -z "${files}" ]; then
      echo "gen-licenses.sh: ${path} にライセンスファイルが見つからない (${dir})" >&2
      exit 1
    fi
    echo "${rule}"
    echo "${path} ${version}"
    echo "${rule}"
    echo
    while read -r f; do
      emit_file "${f}"
    done <<< "${files}"
  done <<< "${mods}"

  # Fyne のテーマは既定フォントを go:embed で抱えており、それがそのまま ferryman の
  # バイナリにも入る。モジュール直下の LICENSE には含まれないので個別に載せる
  fyne_font_dir="$(
    go list -deps -f '{{with .Module}}{{if eq .Path "fyne.io/fyne/v2"}}{{.Dir}}{{end}}{{end}}' \
      ./cmd/ferryman | head -1
  )/theme/font"
  echo "${rule}"
  echo "Fonts embedded by the Fyne toolkit (fyne.io/fyne/v2/theme)"
  echo "${rule}"
  echo
  for f in LICENSE.txt LICENSE_Inter.txt LICENSE_DejaVu-Powerline.txt LICENSE_EmojiOneColor.txt; do
    case "${f}" in
      LICENSE.txt)                  label="NotoSans-Regular/Bold/Italic/BoldItalic.ttf" ;;
      LICENSE_Inter.txt)            label="InterSymbols-Regular.ttf" ;;
      LICENSE_DejaVu-Powerline.txt) label="DejaVuSansMono-Powerline.ttf" ;;
      LICENSE_EmojiOneColor.txt)    label="EmojiOneColor.otf" ;;
    esac
    if [ ! -f "${fyne_font_dir}/${f}" ]; then
      echo "gen-licenses.sh: ${fyne_font_dir}/${f} が無い (Fyne の更新で構成が変わった?)" >&2
      exit 1
    fi
    echo "${rule}"
    echo "${label}"
    echo "${rule}"
    echo
    emit_file "${fyne_font_dir}/${f}"
  done
} > "${tmp}"

mv "${tmp}" "${out}"
trap - EXIT
echo "wrote ${out}"
